---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: Install service
  become: yes
  apt:
    name: apache2
    state: latest
- name: Create content
  template:
    src: index.html
    dest: /var/www/html/index.html
- name: Run service
  service:
    name: apache2
    state: started
